# Generated by Django 4.2 on 2023-04-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
